project:
  type: website

website:
  title: "wildfire"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: sources.qmd
        text: Sources



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



