---
title: "Relationship between wildfire incidents and climate factors"
execute: 
  echo: false
  warning: false
  message: false
---

This project analyzed the relationship between wildfire incidents and climate factors.

The following data was pulled from Kaggle. Then, the relevant data frames were joined to analyze the relationship between wildfire incidents and climate factors (Temperature, Precipitation, Humidity, and Wind Speed).

Based on the visualizations:

Temperature: There seems to be a positive relationship between higher temperatures and increased wildfire incidents. Higher temperatures often coincide with drier conditions, which are more conducive to wildfires.

Precipitation: Generally, lower precipitation levels correlate with more wildfire incidents. Drier conditions with less rainfall lead to increased fire risk.

Humidity: Lower humidity levels tend to correlate with more wildfire incidents. Dry air with low humidity can accelerate fire spread and ignition.

Wind Speed: Higher wind speeds often contribute to the rapid spread of wildfires once ignited, though the exact relationship may vary based on other conditions.

Overall, the relationship between wildfire incidents and these climate factors underscores the importance of weather conditions in wildfire occurrence and severity. Higher temperatures, lower precipitation, lower humidity, and sometimes higher wind speeds tend to increase the likelihood and intensity of wildfires. These factors together influence fire behavior, ignition potential, and the difficulty of fire suppression efforts.


```{r}

# Load libraries
library(dplyr)
library(ggplot2)
library(lubridate)
library(readr)

# Read the datasets
# Load wildfire incidents dataset
wildfire_data <- read.csv("data/California_Fire_Incidents.csv")

# Load CIMIS climate dataset
cimis_data <- read.csv("data/all_conditions.csv")

# Preprocess the wildfire data
# Convert date columns to Date type
wildfire_data$Started <- as.Date(wildfire_data$Started, format = "%Y-%m-%d")
wildfire_data$Ended <- as.Date(wildfire_data$Extinguished, format = "%Y-%m-%d")

#print(head(wildfire_data))

# Aggregate wildfire incidents by month and year
wildfire_data <- wildfire_data %>%
  mutate(Month_Year = format(Started, "%Y-%m")) %>%
  group_by(Month_Year) %>%
  summarise(Incidents = n())

# Check the aggregated data
# print(head(wildfire_data))

# Preprocess the CIMIS data
# Convert date columns to Date type
#cimis_data$Date <- as.Date(cimis_data$Date, format = "%Y-%m-%d")
#cimis_data$Date <- as.Date(cimis_data$Date, format = "%m-%d-%Y")
cimis_data$Date <- as.Date(mdy(cimis_data$Date))
#print(head(cimis_data))
# Aggregate temperature data by month and year
temp_data <- cimis_data %>%
  mutate(Month_Year = format(Date, "%Y-%m")) %>%
  group_by(Month_Year) %>%
  summarise(Average_Temperature = mean(AvgAirTemp, na.rm = TRUE))

#print(head(temp_data))

# Merge the two datasets on Month_Year
merged_data <- merge(wildfire_data, temp_data, by = "Month_Year")

# Check the merged data
#head(merged_data)

# Plot the relationship between wildfire incidents and temperature
ggplot(data = merged_data, aes(x = Average_Temperature, y = Incidents)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(title = "Relationship between Wildfire Incidents and Temperature",
       x = "Average Temperature (°F)",
       y = "Number of Wildfire Incidents") +
  theme_minimal()

#####
# Aggregate Precipitation data by month and year
Precip_data <- cimis_data %>%
  mutate(Month_Year = format(Date, "%Y-%m")) %>%
  group_by(Month_Year) %>%
  summarise(Average_Precip = mean(Precip, na.rm = TRUE))

# Merge the two datasets on Month_Year
merged_data <- merge(wildfire_data, Precip_data, by = "Month_Year")

# Plot the relationship between wildfire incidents and temperature
ggplot(data = merged_data, aes(x = Average_Precip, y = Incidents)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(title = "Relationship between Wildfire Incidents and Precipitation",
       x = "Precipitation (in)",
       y = "Number of Wildfire Incidents") +
  theme_minimal()

#####
# Aggregate Humidity data by month and year
AvgRelHum_data <- cimis_data %>%
  mutate(Month_Year = format(Date, "%Y-%m")) %>%
  group_by(Month_Year) %>%
  summarise(Average_AvgRelHum = mean(AvgRelHum, na.rm = TRUE))

# Merge the two datasets on Month_Year
merged_data <- merge(wildfire_data, AvgRelHum_data, by = "Month_Year")

# Plot the relationship between wildfire incidents and temperature
ggplot(data = merged_data, aes(x = Average_AvgRelHum, y = Incidents)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(title = "Relationship between Wildfire Incidents and Humidity",
       x = "Humidity %",
       y = "Number of Wildfire Incidents") +
  theme_minimal()

#####
# Aggregate Wind Speed data by month and year
AvgWindSpeed_data <- cimis_data %>%
  mutate(Month_Year = format(Date, "%Y-%m")) %>%
  group_by(Month_Year) %>%
  summarise(Average_AvgWindSpeed = mean(AvgWindSpeed, na.rm = TRUE))

# Merge the two datasets on Month_Year
merged_data <- merge(wildfire_data, AvgWindSpeed_data, by = "Month_Year")

# Plot the relationship between wildfire incidents and temperature
ggplot(data = merged_data, aes(x = Average_AvgWindSpeed, y = Incidents)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(title = "Relationship between Wildfire Incidents and Wind Speed",
       x = "Wind Speed (mpg)",
       y = "Number of Wildfire Incidents") +
  theme_minimal()
```

